/*
 Navicat Premium Data Transfer

 Source Server         : localmysql
 Source Server Type    : MySQL
 Source Server Version : 80017
 Source Host           : localhost:3306
 Source Schema         : pks

 Target Server Type    : MySQL
 Target Server Version : 80017
 File Encoding         : 65001

 Date: 16/03/2020 19:28:43
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for admin
-- ----------------------------
DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin`  (
  `Username` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`Username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for park
-- ----------------------------
DROP TABLE IF EXISTS `park`;
CREATE TABLE `park`  (
  `Parkno` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Carno` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `Cartype` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `Intime` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`Parkno`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of park
-- ----------------------------
INSERT INTO `park` VALUES ('A0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('A9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('B9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('C9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('D9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('E9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('F9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('G9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('H9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('I9', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J0', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J1', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J2', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J3', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J4', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J5', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J6', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J7', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J8', NULL, NULL, NULL);
INSERT INTO `park` VALUES ('J9', NULL, NULL, NULL);

-- ----------------------------
-- Table structure for recond
-- ----------------------------
DROP TABLE IF EXISTS `recond`;
CREATE TABLE `recond`  (
  `Parkno` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Carno` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Cartype` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Intime` datetime(0) NULL DEFAULT NULL,
  `Outtime` datetime(0) NULL DEFAULT NULL,
  `Waittime` int(11) NULL DEFAULT NULL,
  `Cost` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Parkno`, `Carno`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
